export const stores=[
    {   id:1,image:require("./../photos/Abris et stores/1.jpg")},
    {   id:2,image:require("./../photos/Abris et stores/5.jpg")},
    {   id:3,image:require("./../photos/Abris et stores/6.jpg")},
    {   id:4,image:require("./../photos/Abris et stores/7.jpg")},
    {   id:5,image:require("./../photos/Abris et stores/3.jpg")},
    {   id:6,image:require("./../photos/Abris et stores/2.jpg")},
    {   id:7,image:require("./../photos/Abris et stores/8.jpg")},
    {   id:8,image:require("./../photos/Abris et stores/9.jpg")},
    {   id:9,image:require("./../photos/Abris et stores/10.jpg")},
    {   id:10,image:require("./../photos/Abris et stores/11.jpg")},
    {   id:11,image:require("./../photos/Abris et stores/12.jpg")},
    {   id:12,image:require("./../photos/Abris et stores/13.jpg")},
    {   id:13,image:require("./../photos/Abris et stores/14.jpg")},
    {   id:14,image:require("./../photos/Abris et stores/15.jpg")},
    {   id:15,image:require("./../photos/Abris et stores/16.jpeg")},
    {   id:16,image:require("./../photos/Abris et stores/17.jpg")},
    {   id:17,image:require("./../photos/Abris et stores/18.jpg")},
    {   id:18,image:require("./../photos/Abris et stores/19.jpg")},
    {   id:19,image:require("./../photos/Abris et stores/20.jpg")},
    {   id:20,image:require("./../photos/Abris et stores/21.jpg")},
    {   id:21,image:require("./../photos/Abris et stores/23.jpg")},
    {   id:22,image:require("./../photos/Abris et stores/24.jpg")},
    {   id:23,image:require("./../photos/Abris et stores/25.jpg")},
    {   id:24,image:require("./../photos/Abris et stores/26.jpg")},
    {   id:25,image:require("./../photos/Abris et stores/29.jpg")},
    {   id:26,image:require("./../photos/Abris et stores/30.jpg")},
    {   id:27,image:require("./../photos/Abris et stores/31.jpg")},
    {   id:28,image:require("./../photos/Abris et stores/32.jpg")},
    {   id:29,image:require("./../photos/Abris et stores/35.jpg")},
    {   id:30,image:require("./../photos/Abris et stores/36.jpg")},
    {   id:31,image:require("./../photos/Abris et stores/38.JPG")},
    {   id:32,image:require("./../photos/Abris et stores/39.JPG")},
    {   id:33,image:require("./../photos/Abris et stores/41.JPG")},
    {   id:34,image:require("./../photos/Abris et stores/42.jpeg")},

]

export const impression=[
    {   id:1,image:require("./../photos/Impression numerique et habillage/1.jpg")},
    {   id:2,image:require("./../photos/Impression numerique et habillage/2.jpg")},
    {   id:3,image:require("./../photos/Impression numerique et habillage/3.jpg")},
    {   id:5,image:require("./../photos/Impression numerique et habillage/5.jpg")},
    {   id:6,image:require("./../photos/Impression numerique et habillage/6.jpg")},
    {   id:7,image:require("./../photos/Impression numerique et habillage/7.jpg")},
    {   id:8,image:require("./../photos/Impression numerique et habillage/8.jpg")},
    {   id:9,image:require("./../photos/Impression numerique et habillage/9.jpg")},
    {   id:10,image:require("./../photos/Impression numerique et habillage/10.jpg")},
    {   id:11,image:require("./../photos/Impression numerique et habillage/11.jpg")},
    {   id:12,image:require("./../photos/Impression numerique et habillage/12.jpg")},
   
]

export const rev=[
    {   id:1,image:require("./../photos/Revetement de facade et enseigne/1.jpg")},
    {   id:2,image:require("./../photos/Revetement de facade et enseigne/2.jpg")},
    {   id:3,image:require("./../photos/Revetement de facade et enseigne/3.jpg")},
    {   id:4,image:require("./../photos/Revetement de facade et enseigne/4.jpeg")},
    {   id:5,image:require("./../photos/Revetement de facade et enseigne/5.jpg")},
    {   id:6,image:require("./../photos/Revetement de facade et enseigne/6.jpg")},
    {   id:7,image:require("./../photos/Revetement de facade et enseigne/7.jpg")},
    {   id:9,image:require("./../photos/Revetement de facade et enseigne/9.jpg")},
    {   id:10,image:require("./../photos/Revetement de facade et enseigne/10.jpg")},
    {   id:11,image:require("./../photos/Revetement de facade et enseigne/11.jpg")},
   
]